# Generated by Django 4.1.7 on 2023-02-17 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ecoplatform.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_photo_main', models.ImageField(upload_to=ecoplatform.models.Project.get_image_path)),
                ('project_photo_1', models.ImageField(blank=True, upload_to=ecoplatform.models.Project.get_image_path)),
                ('project_photo_2', models.ImageField(blank=True, upload_to=ecoplatform.models.Project.get_image_path)),
                ('project_photo_3', models.ImageField(blank=True, upload_to=ecoplatform.models.Project.get_image_path)),
                ('project_photo_4', models.ImageField(blank=True, upload_to=ecoplatform.models.Project.get_image_path)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('isTrending', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecoplatform.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem_photo_main', models.ImageField(upload_to=ecoplatform.models.Problem.get_image_path)),
                ('problem_photo_1', models.ImageField(blank=True, upload_to=ecoplatform.models.Problem.get_image_path)),
                ('problem_photo_2', models.ImageField(blank=True, upload_to=ecoplatform.models.Problem.get_image_path)),
                ('problem_photo_3', models.ImageField(blank=True, upload_to=ecoplatform.models.Problem.get_image_path)),
                ('problem_photo_4', models.ImageField(blank=True, upload_to=ecoplatform.models.Problem.get_image_path)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('isTrending', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecoplatform.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
            },
        ),
    ]
