# Generated by Django 4.1.7 on 2023-03-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoplatform', '0002_rename_owner_problem_user_rename_owner_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='problem_photo_4',
        ),
        migrations.AddField(
            model_name='problem',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
