# Generated by Django 4.1.7 on 2023-03-25 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecoplatform', '0004_remove_project_project_photo_4_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
