# Generated by Django 4.1.7 on 2023-03-25 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecoplatform', '0005_project_downvotes_project_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_problems', to=settings.AUTH_USER_MODEL),
        ),
    ]
